task:
    name: Build_Rom
    CIRRUS_CLONE_DEPTH: 1

    container:
        image: ghcr.io/sushrut1101/docker:arch
        cpu: 24
        memory: 64G
        volumes:
          - /home/cirrus/roms:/home/cirrus/voltageos
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config

    env:
        GH_TOKEN: ENCRYPTED[915f3caa16328343227e415f7c78e85098992b465c226fd933d507cd8c4b704a608f7b57ef2e7ddcee58516fd3bc09b2]

    Setup_script: bash setup.sh

    Clone_script: bash clone.sh

    Build_script: bash build.sh

    Upload_script:
         - bash "$OUT_FILE" upload.sh
         - gh release create "v-$BUILD_TIME" "$OUT_FILE" --generate-notes
